language: node_js

matrix:
  include:
    - node_js: '8.9'
    - node_js: '10.6'
      env:
        - INTEGRATION_TESTS=true
    - node_js: '10.6'
      env:
        - DISABLE_TESTS=true
        - LINTING=true

sudo: false

install:
  - travis_retry npm install

script:
  - if [[ -z "$DISABLE_TESTS" ]]; then npm run test; fi
  - if [[ ! -z "$DISABLE_TESTS" && ! -z "$LINTING" ]]; then npm run lint; fi
  - if [[ ! -z "$INTEGRATION_TESTS" && $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then npm run integration-test; fi

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
